version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn --version
      
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
      
  build:
    commands:
      - echo Building and packaging application...
      - mvn compile
      - mvn package -DskipTests
      
  post_build:
    commands:
      - echo Build completed successfully
      
artifacts:
  # 1) base-directory: "." → incluye archivos desde la raíz del proyecto
  base-directory: "."

  # 2) files: incluye el JAR y archivos de configuración
  files:
    - "target/*.jar"
    - "Procfile"
    - ".ebextensions/**/*"

  # 3) discard-paths: no → mantiene la estructura de directorios
  discard-paths: no

  # 4) name: así se llamará el ZIP que se suba a S3
  name: finnancy-backend-artifact.zip
